# Generated by Django 3.2.12 on 2022-03-30 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Please provide description for this product, description is required for better understanding', help_text='Please provide description for this product, description is required for better understanding'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique name for product', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
