# Generated by Django 3.2.12 on 2022-03-31 18:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220331_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='Image must be png and size of 250*250', keep_meta=True, null=True, quality=75, size=[250, 250], upload_to='product/category/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(default='fa fa-list', max_length=255),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='Image must be png and size of 150*150', keep_meta=True, null=True, quality=75, size=[150, 150], upload_to='product/category/'),
        ),
    ]
